name: Release Workflow

on:
  push:
    tags: [ '**' ]
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

jobs:

  build-and-run-tests:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:

      - name: Set Branch Name
        uses: nelonoel/branch-name@v1.0.1

      - name: Set GitHub Tag environment variable
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          TAG_ID=${GITHUB_REF##*/}
          echo "ACTIONS_TAG=$TAG_ID" >> $GITHUB_ENV

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '8'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copyright Check
        run: ./copyrightCheck.sh

      - name: Gradle Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        run: |
          ./gradlew clean build shadowJar

      - name: Gradle Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        run: ./gradlew publish

      - name: Post Slack Update
        if: ${{ job.status == 'failure' }}
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: "{\"Repo\":\"${{ github.repository }}\",\"Workflow\":\"${{ github.workflow }}\",\"Branch\":\"${{ env.BRANCH_NAME }}\",\"Link\":\"https://github.com/Alvearie/hri-mgmt-api/actions/runs/${{ github.run_id }}\"}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}